const dummyData = [
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category", featured: true} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category", featured: true} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category", featured: true} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category", featured: true} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
    { _source: {title: "Tenis blancos talla 32 New Balance Nuevos", discount: 50, imageLink: "https://static.dafiti.com.co/p/adidas-performance-2335-7631181-1-catalog-new.jpg", link: "https://www.dafiti.com.co/Tenis-Gris-adidas-Performance-GALAXY-5-1811367.html", provider: "Dafiti", category: "Category"} },
]

module.exports = { dummyData }